[project]
name = "data-proc-benchmark"
version = "0.1.3"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.3.2",
    "fireducks>=1.4.2; sys_platform != 'win32'",
    "gputil>=1.4.0",
    "ipykernel>=7.1.0",
    "numpy>=2.3.2",
    "pandas>=2.3.2",
    "parquet>=1.3.1",
    "polars>=1.32.3",
    "psutil>=7.1.0",
    "py-cpuinfo>=9.0.0",
    "pyarrow>=21.0.0",
    "ruff>=0.15.14",
    "typing-extensions>=4.14.1",
    "wmi>=1.5.1; sys_platform == 'win32'",
]
